on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'oracle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup gradle cache
        uses: burrunan/gradle-cache-action@v2
        with:
          save-gradle-dependencies-cache: true
          save-maven-dependencies-cache: false
          save-local-build-cache: false
          save-generated-gradle-jars: false
          maven-local-ignore-paths: |
            org/teleight
      - name: Build with Gradle
        run: ./gradlew build
